name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: '${{ secrets.DEPLOY_KEY }}'

      - name: Clean install dependencies
        run: |
            rm -rf node_modules package-lock.json
            npm install

      - name: Build the project
        run: npm run build

      - name: Deploy to Server
        env:
          REMOTE_DIR: /var/www/3dworld/dist
        run: |
          # Clear the old build
          ssh -o StrictHostKeyChecking=no megaserver@megaworld.xyz "rm -rf $REMOTE_DIR/*"

          # Copy the new build
          scp -o StrictHostKeyChecking=no -r dist/* megaserver@megaworld.xyz:$REMOTE_DIR

          # Reload Nginx
          ssh -o StrictHostKeyChecking=no megaserver@megaworld.xyz "sudo -n systemctl reload nginx"
